### ISSUE TITLE
Out shows blank

### ISSUE THREAD

**Issue by diptnc** [bbonik/facial-landmark-frontalization#1]
![Capture](https://user-images.githubusercontent.com/35225642/111910395-320f1780-8a87-11eb-94c4-1cc44c08f014.JPG)

I get the following blank output. what is the possible reason?

**Comment by bbonik** [comment]
This could be due to many things. We have to troubleshoot. Are you able to get back facial landmarks with other images? If not, then there may be an issue with the installation or version of DLIB.

**Comment by diptnc** [comment]
![image](https://user-images.githubusercontent.com/35225642/111951721-0c772200-8b0a-11eb-9390-09f5e247b94f.png)
ya checked with other images . Output is same

**Comment by diptnc** [comment]
![image](https://user-images.githubusercontent.com/35225642/111952020-78f22100-8b0a-11eb-9825-773935b1534f.png)
 ya checked with other images ,the results are same

**Comment by bbonik** [comment]
Can you please print what is the output of lines 29 and 30 from the example_frontalize_dlib_singleimage.py when you try with an image? For these 2 lines of code:
landmarks_raw = predictor(image, face)  # detect landmarks
landmarks = get_landmark_array(landmarks_raw)

specifically, check what is the "landmarks_raw" and "landmarks" variables. What type and what values they have. This will help us understand what's going on...
