### ISSUE TITLE
Dlib

### ISSUE THREAD

**Issue by jayp84847** [bbonik/facial-landmark-frontalization#4]
Yet I am using dlib 68_face_landmarks.dat in my project but it's not stable and accurate so any suggestions to make it more stable and accurate.

**Comment by bbonik** [comment]
Can you elaborate more on what do you mean by "stable" and "accurate"? You refer to the initial DLIB landmarks or the frontalized ones? From my experience, DLIB landmarks are not stable. They fluctuate a lot and are affected by uneven illumination (like shadows or directional light), facial hair and dark skin. This has to do probably with the dataset that they were trained with, which, as users, we cannot control. The best conditions for DLIB landmarks to be stable are, black facial features over white-tone skin face, no facial hair or accessories, illumination behind the camera, no illumination behind or on top/sideways of the face. Any deviation from these conditions makes the DLIB landmarks fluctuate. The frontalized landmarks are based on the original DLIB landmarks. So, if the original landmarks are fluctuating a lot, then these fluctuations will also affect the frontalized landmarks.

**Comment by jayp84847** [comment]
Stable and accurate mean by I want to make as stable as snapchat facial landmarks. Like dlib's 68_face_landmarks.dat module works, but not working for rotational faces and even not working when user tries with glasses. 

Also cause of less accuracy, when I deployed face mesh of cat(example) it seems like vibrating. Not stable.

Can you share your mail. I will share you my current result video. Unable to send it on github.

**Comment by bbonik** [comment]
You can contact me at bbonik@gmail.com
